[package]
name = "oxcable"
version = "0.3.2"
authors = ["Michael Nye <thenyeguy@gmail.com>"]
license = "CC-BY-NC-4.0"
homepage = "https://github.com/thenyeguy/oxcable"
repository = "https://github.com/thenyeguy/oxcable"
documentation = "http://thenyeguy.github.io/oxcable/doc/oxcable/index.html"
description = "A simple audio processing and MIDI framework in Rust."
exclude= [ "wav/*" ]

[lib]
name = "oxcable"
path = "src/oxcable.rs"

[dependencies]
byteorder = "*"
portmidi = "*"
num = { version = "*", default-features = false }
portaudio = "*"
rand = "*"
