[package]
name = "OxilaryCable"
version = "0.0.1"
authors = ["Michael Nye <thenyeguy@gmail.com>"]

[lib]
name = "oxcable"
path = "src/oxcable.rs"

[dependencies.rust-portaudio]
git = "https://github.com/jeremyletang/rust-portaudio.git"

[dependencies.portmidi]
git = "https://github.com/musitdev/rust-portmidi.git"
