[package]
name = "oxcable"
version = "0.3.0"
authors = ["Michael Nye <thenyeguy@gmail.com>"]
license = "Creative Commons BY-NC-SA 4.0"
repository = "https://github.com/thenyeguy/OxilaryCable"
description = "A simple audio processing and MIDI framework in Rust."

[lib]
name = "oxcable"
path = "src/oxcable.rs"

[dependencies]
byteorder = "*"
portmidi = "*"
num = { version = "*", default-features = false }
portaudio = "*"
rand = "*"
